-- Estrutura da instalação exclusiva da Lu Fashion Hair.
-- Projeto: ezhaitxgmpqcgjramfiu (região São Paulo).

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 1 and 255),
  telefone text check (telefone is null or char_length(telefone) <= 30),
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.servicos (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 1 and 255),
  duracao_minutos integer not null default 60 check (duracao_minutos between 15 and 1440),
  preco numeric(10,2) check (preco is null or preco >= 0),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  cliente_id bigint references public.clientes(id) on delete set null,
  cliente_nome text not null check (char_length(trim(cliente_nome)) between 1 and 255),
  servico_id bigint references public.servicos(id) on delete set null,
  servico_nome text not null check (char_length(trim(servico_nome)) between 1 and 255),
  data date not null,
  hora time not null,
  status text not null default 'agendado' check (status in ('agendado','confirmado','em_andamento','concluido','faltou','cancelado')),
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists agendamentos_horario_ativo_uidx on public.agendamentos(owner_id, data, hora) where status not in ('cancelado','faltou');
create index if not exists clientes_owner_nome_idx on public.clientes(owner_id, nome);
create index if not exists servicos_owner_nome_idx on public.servicos(owner_id, nome);
create index if not exists agendamentos_owner_data_idx on public.agendamentos(owner_id, data, hora);

alter table public.clientes enable row level security;
alter table public.servicos enable row level security;
alter table public.agendamentos enable row level security;

revoke all on public.clientes, public.servicos, public.agendamentos from anon;
grant select, insert, update, delete on public.clientes, public.servicos, public.agendamentos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy clientes_owner_select on public.clientes for select to authenticated using ((select auth.uid()) = owner_id);
create policy clientes_owner_insert on public.clientes for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy clientes_owner_update on public.clientes for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy clientes_owner_delete on public.clientes for delete to authenticated using ((select auth.uid()) = owner_id);
create policy servicos_owner_select on public.servicos for select to authenticated using ((select auth.uid()) = owner_id);
create policy servicos_owner_insert on public.servicos for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy servicos_owner_update on public.servicos for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy servicos_owner_delete on public.servicos for delete to authenticated using ((select auth.uid()) = owner_id);
create policy agendamentos_owner_select on public.agendamentos for select to authenticated using ((select auth.uid()) = owner_id);
create policy agendamentos_owner_insert on public.agendamentos for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy agendamentos_owner_update on public.agendamentos for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy agendamentos_owner_delete on public.agendamentos for delete to authenticated using ((select auth.uid()) = owner_id);
