-- Completa o sistema da Lu Fashion Hair sem apagar os dados existentes.

create extension if not exists pg_cron with schema pg_catalog;

alter table public.clientes
  add column if not exists deleted_at timestamptz;

update public.clientes
set deleted_at = coalesce(deleted_at, updated_at, now())
where ativo = false and deleted_at is null;

alter table public.agendamentos
  add column if not exists duracao_minutos integer not null default 60
    check (duracao_minutos between 15 and 1440),
  add column if not exists valor_servico numeric(10,2)
    check (valor_servico is null or valor_servico >= 0);

update public.agendamentos a
set duracao_minutos = s.duracao_minutos,
    valor_servico = coalesce(a.valor_servico, s.preco)
from public.servicos s
where a.servico_id = s.id;

create table if not exists public.pagamentos (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  agendamento_id bigint not null unique references public.agendamentos(id) on delete cascade,
  valor_servico numeric(10,2) not null default 0 check (valor_servico >= 0),
  desconto numeric(10,2) not null default 0 check (desconto >= 0),
  valor_pago numeric(10,2) not null default 0 check (valor_pago >= 0),
  status text not null default 'pendente' check (status in ('pendente','parcial','pago')),
  forma_pagamento text check (forma_pagamento is null or forma_pagamento in ('pix','dinheiro','debito','credito','transferencia','outro')),
  data_pagamento date,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.pagamentos (owner_id, agendamento_id, valor_servico)
select a.owner_id, a.id, coalesce(a.valor_servico, 0)
from public.agendamentos a
on conflict (agendamento_id) do nothing;

create table if not exists public.despesas (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  descricao text not null check (char_length(trim(descricao)) between 1 and 255),
  categoria text not null default 'outros' check (categoria in ('produtos','materiais','aluguel','energia','agua','internet','transporte','manutencao','outros')),
  valor numeric(10,2) not null check (valor > 0),
  data date not null default current_date,
  pago boolean not null default true,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.formatar_nome(valor text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select initcap(lower(regexp_replace(trim(valor), '\s+', ' ', 'g')));
$$;

create or replace function public.preparar_cliente()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.nome := public.formatar_nome(new.nome);
  if new.deleted_at is null then
    new.ativo := true;
  else
    new.ativo := false;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists clientes_preparar_trg on public.clientes;
create trigger clientes_preparar_trg
before insert or update on public.clientes
for each row execute function public.preparar_cliente();

create or replace function public.preparar_servico()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.nome := public.formatar_nome(new.nome);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists servicos_preparar_trg on public.servicos;
create trigger servicos_preparar_trg
before insert or update on public.servicos
for each row execute function public.preparar_servico();

create or replace function public.preparar_agendamento()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  inicio_novo timestamp;
  fim_novo timestamp;
begin
  if new.cliente_id is not null then
    select c.nome into new.cliente_nome
    from public.clientes c
    where c.id = new.cliente_id and c.owner_id = new.owner_id;
  else
    new.cliente_nome := public.formatar_nome(new.cliente_nome);
  end if;

  if new.servico_id is not null and (tg_op = 'INSERT' or new.servico_id is distinct from old.servico_id) then
    select s.nome, s.duracao_minutos, s.preco
      into new.servico_nome, new.duracao_minutos, new.valor_servico
    from public.servicos s
    where s.id = new.servico_id and s.owner_id = new.owner_id;
  end if;

  new.updated_at := now();

  if new.status not in ('cancelado','faltou') then
    inicio_novo := new.data + new.hora;
    fim_novo := inicio_novo + make_interval(mins => new.duracao_minutos);
    if exists (
      select 1
      from public.agendamentos a
      where a.owner_id = new.owner_id
        and a.id <> coalesce(new.id, 0)
        and a.status not in ('cancelado','faltou')
        and tsrange(a.data + a.hora, a.data + a.hora + make_interval(mins => a.duracao_minutos), '[)')
            && tsrange(inicio_novo, fim_novo, '[)')
    ) then
      raise exception 'Esse horario conflita com outro atendimento. Escolha outro horario.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists agendamentos_preparar_trg on public.agendamentos;
create trigger agendamentos_preparar_trg
before insert or update on public.agendamentos
for each row execute function public.preparar_agendamento();

create or replace function public.sincronizar_pagamento_agendamento()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.pagamentos (owner_id, agendamento_id, valor_servico)
  values (new.owner_id, new.id, coalesce(new.valor_servico, 0))
  on conflict (agendamento_id) do update
    set valor_servico = excluded.valor_servico,
        updated_at = now()
    where public.pagamentos.valor_pago = 0;
  return new;
end;
$$;

drop trigger if exists agendamentos_pagamento_trg on public.agendamentos;
create trigger agendamentos_pagamento_trg
after insert or update of valor_servico, servico_id on public.agendamentos
for each row execute function public.sincronizar_pagamento_agendamento();

create or replace function public.preparar_pagamento()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  total numeric(10,2);
begin
  total := greatest(new.valor_servico - new.desconto, 0);
  if new.valor_pago <= 0 then
    new.status := 'pendente';
    new.data_pagamento := null;
    new.forma_pagamento := null;
  elsif new.valor_pago < total then
    new.status := 'parcial';
    new.data_pagamento := coalesce(new.data_pagamento, current_date);
  else
    new.status := 'pago';
    new.valor_pago := total;
    new.data_pagamento := coalesce(new.data_pagamento, current_date);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pagamentos_preparar_trg on public.pagamentos;
create trigger pagamentos_preparar_trg
before insert or update on public.pagamentos
for each row execute function public.preparar_pagamento();

create or replace function public.refletir_cliente_agendamentos()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.nome is distinct from old.nome then
    update public.agendamentos
    set cliente_nome = new.nome, updated_at = now()
    where owner_id = new.owner_id and cliente_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists clientes_refletir_trg on public.clientes;
create trigger clientes_refletir_trg
after update of nome on public.clientes
for each row execute function public.refletir_cliente_agendamentos();

create or replace function public.refletir_servico_agendamentos()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.nome is distinct from old.nome
     or new.duracao_minutos is distinct from old.duracao_minutos
     or new.preco is distinct from old.preco then
    update public.agendamentos
    set servico_nome = new.nome,
        duracao_minutos = new.duracao_minutos,
        valor_servico = new.preco,
        updated_at = now()
    where owner_id = new.owner_id
      and servico_id = new.id
      and data >= current_date
      and status in ('agendado','confirmado','em_andamento');
  end if;
  return new;
end;
$$;

drop trigger if exists servicos_refletir_trg on public.servicos;
create trigger servicos_refletir_trg
after update of nome, duracao_minutos, preco on public.servicos
for each row execute function public.refletir_servico_agendamentos();

create index if not exists clientes_owner_lixeira_idx on public.clientes(owner_id, deleted_at) where deleted_at is not null;
create index if not exists pagamentos_owner_status_idx on public.pagamentos(owner_id, status);
create index if not exists despesas_owner_data_idx on public.despesas(owner_id, data);

alter table public.pagamentos enable row level security;
alter table public.despesas enable row level security;

revoke all on public.pagamentos, public.despesas from anon;
grant select, insert, update, delete on public.pagamentos, public.despesas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists pagamentos_owner_select on public.pagamentos;
drop policy if exists pagamentos_owner_insert on public.pagamentos;
drop policy if exists pagamentos_owner_update on public.pagamentos;
drop policy if exists pagamentos_owner_delete on public.pagamentos;
create policy pagamentos_owner_select on public.pagamentos for select to authenticated using ((select auth.uid()) = owner_id);
create policy pagamentos_owner_insert on public.pagamentos for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy pagamentos_owner_update on public.pagamentos for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy pagamentos_owner_delete on public.pagamentos for delete to authenticated using ((select auth.uid()) = owner_id);

drop policy if exists despesas_owner_select on public.despesas;
drop policy if exists despesas_owner_insert on public.despesas;
drop policy if exists despesas_owner_update on public.despesas;
drop policy if exists despesas_owner_delete on public.despesas;
create policy despesas_owner_select on public.despesas for select to authenticated using ((select auth.uid()) = owner_id);
create policy despesas_owner_insert on public.despesas for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy despesas_owner_update on public.despesas for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy despesas_owner_delete on public.despesas for delete to authenticated using ((select auth.uid()) = owner_id);

do $$
declare trabalho record;
begin
  for trabalho in select jobid from cron.job where jobname = 'limpar-lixeira-clientes-lu-fashion' loop
    perform cron.unschedule(trabalho.jobid);
  end loop;
end $$;

select cron.schedule(
  'limpar-lixeira-clientes-lu-fashion',
  '15 3 * * *',
  $$delete from public.clientes where deleted_at is not null and deleted_at <= now() - interval '3 days'$$
);

update public.clientes set nome = nome;
update public.servicos set nome = nome;

